from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from legal_workbench.domain.documents import (
    DocumentExtraction,
    DocumentSegment,
    DocumentVersion,
    FeishuDocument,
    FeishuDocumentSubscription,
)
from legal_workbench.domain.knowledge import (
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeRetrievalLog,
)

__all__ = [
    "AttachmentStorageQuotaRepository",
    "DocumentRepository",
    "KnowledgeRepository",
]


class DocumentRepository(Protocol):
    async def find_feishu_document(
        self, *, authorization_id: UUID, document_token: str
    ) -> FeishuDocument | None: ...
    async def add_feishu_document(self, value: FeishuDocument) -> None: ...
    async def save_feishu_document(self, value: FeishuDocument) -> None: ...
    async def add_feishu_message_document_link(
        self, *, message_id: UUID, document_id: UUID, source_url: str
    ) -> None: ...
    async def get_feishu_document_subscription(
        self, *, authorization_id: UUID, folder_token: str
    ) -> FeishuDocumentSubscription | None: ...
    async def get_feishu_document_subscription_by_id(
        self, subscription_id: UUID
    ) -> FeishuDocumentSubscription | None: ...
    async def list_feishu_document_subscriptions(
        self, *, authorization_id: UUID | None = None, active_only: bool = False
    ) -> Sequence[FeishuDocumentSubscription]: ...
    async def add_feishu_document_subscription(
        self, value: FeishuDocumentSubscription
    ) -> None: ...
    async def save_feishu_document_subscription(
        self, value: FeishuDocumentSubscription
    ) -> None: ...
    async def find_feishu_document_version(
        self, *, document_id: UUID, content_sha256: str
    ) -> DocumentVersion | None: ...
    async def next_feishu_document_version(self, document_id: UUID) -> int: ...
    async def find_version(
        self, *, attachment_id: UUID, content_sha256: str
    ) -> DocumentVersion | None: ...
    async def next_version(self, attachment_id: UUID) -> int: ...
    async def add_version(self, version: DocumentVersion) -> None: ...
    async def add_extraction(self, extraction: DocumentExtraction) -> None: ...
    async def find_latest_extraction(
        self, document_version_id: UUID
    ) -> DocumentExtraction | None: ...
    async def get_extraction_for_update(self, extraction_id: UUID) -> DocumentExtraction | None: ...
    async def save_extraction(self, extraction: DocumentExtraction) -> None: ...
    async def get_version(self, version_id: UUID) -> DocumentVersion | None: ...
    async def add_segments(self, segments: Sequence[DocumentSegment]) -> None: ...
    async def list_latest_segments(
        self, attachment_ids: Sequence[UUID]
    ) -> Sequence[DocumentSegment]: ...
    async def list_latest_feishu_segments_for_messages(
        self, message_ids: Sequence[UUID]
    ) -> Sequence[tuple[FeishuDocument, DocumentSegment]]: ...


class KnowledgeRepository(Protocol):
    async def add_document(self, document: KnowledgeDocument) -> None: ...
    async def get_document(self, document_id: UUID) -> KnowledgeDocument | None: ...
    async def find_document_by_source(
        self, *, source_type: str, source_id: str
    ) -> KnowledgeDocument | None: ...
    async def add_chunks(self, chunks: Sequence[KnowledgeChunk]) -> None: ...
    async def list_chunks(self, document_id: UUID) -> Sequence[KnowledgeChunk]: ...
    async def add_retrieval_log(self, log: KnowledgeRetrievalLog) -> None: ...


class AttachmentStorageQuotaRepository(Protocol):
    async def reserve(
        self,
        *,
        attachment_id: UUID,
        requested_bytes: int,
        total_bytes: int,
        observed_used_bytes: int,
        expires_at: datetime,
    ) -> UUID | None: ...
    async def commit(self, reservation_token: UUID) -> None: ...
    async def release(self, reservation_token: UUID) -> None: ...
