from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from legal_workbench.domain.enums import (
    FeishuMessageStatus,
)
from legal_workbench.domain.feishu import (
    FeishuAttachment,
    FeishuMessage,
    FeishuMessageVersion,
    FeishuOAuthAttempt,
    FeishuRawEvent,
    FeishuSyncCheckpoint,
    FeishuUserAuthorization,
    IntegrationConnection,
    MessageAttachment,
)

__all__ = [
    "FeishuPersonalSyncRepository",
    "FeishuRepository",
    "FeishuUserAuthorizationRepository",
]

class FeishuRepository(Protocol):
    async def get_event_by_external_id(
        self, event_id: str, *, tenant_key: str | None = None
    ) -> FeishuRawEvent | None: ...
    async def add_event(self, event: FeishuRawEvent) -> None: ...
    async def get_message(
        self, *, tenant_key: str | None, message_id: str
    ) -> FeishuMessage | None: ...
    async def add_message(self, message: FeishuMessage) -> None: ...
    async def get_message_by_id(self, message_id: UUID) -> FeishuMessage | None: ...
    async def get_message_for_update(self, message_id: UUID) -> FeishuMessage | None: ...
    async def list_context_messages(
        self, message: FeishuMessage, *, limit: int
    ) -> Sequence[FeishuMessage]: ...
    async def list_messages(
        self,
        *,
        statuses: Sequence[FeishuMessageStatus] | None,
        search: str | None,
        chat_id: str | None,
        created_from: datetime | None,
        created_to: datetime | None,
        limit: int,
    ) -> Sequence[FeishuMessage]: ...
    async def save_message(self, message: FeishuMessage) -> None: ...
    async def next_message_revision(self, message_id: UUID) -> int: ...
    async def add_message_version(self, version: FeishuMessageVersion) -> None: ...
    async def list_message_versions(self, message_id: UUID) -> Sequence[FeishuMessageVersion]: ...
    async def add_attachments(self, attachments: Sequence[FeishuAttachment]) -> None: ...
    async def list_pending_attachments(self, message_id: UUID) -> Sequence[FeishuAttachment]: ...
    async def list_attachments(self, message_id: UUID) -> Sequence[FeishuAttachment]: ...
    async def get_attachment_for_update(self, attachment_id: UUID) -> MessageAttachment | None: ...
    async def save_attachment(self, attachment: FeishuAttachment) -> None: ...
    async def list_queued_without_active_run(self, *, limit: int) -> Sequence[FeishuMessage]: ...
    async def get_connection(
        self, *, integration_type: str, connection_mode: object
    ) -> IntegrationConnection | None: ...
    async def save_connection(self, connection: IntegrationConnection) -> None: ...


class FeishuUserAuthorizationRepository(Protocol):
    async def add_oauth_attempt(self, value: FeishuOAuthAttempt) -> None: ...
    async def get_oauth_attempt_for_update(
        self, state_hash: str
    ) -> FeishuOAuthAttempt | None: ...
    async def save_oauth_attempt(self, value: FeishuOAuthAttempt) -> None: ...
    async def add_authorization(self, value: FeishuUserAuthorization) -> None: ...
    async def get_authorization(
        self, authorization_id: UUID
    ) -> FeishuUserAuthorization | None: ...
    async def get_authorization_for_update(
        self, authorization_id: UUID
    ) -> FeishuUserAuthorization | None: ...
    async def save_authorization(self, value: FeishuUserAuthorization) -> None: ...
    async def list_authorizations(self) -> Sequence[FeishuUserAuthorization]: ...


class FeishuPersonalSyncRepository(Protocol):
    async def get_checkpoint_for_update(
        self, *, authorization_id: UUID, scope_id: UUID
    ) -> FeishuSyncCheckpoint | None: ...
    async def add_checkpoint(self, value: FeishuSyncCheckpoint) -> None: ...
    async def save_checkpoint(self, value: FeishuSyncCheckpoint) -> None: ...
