from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from legal_workbench.domain.enums import (
    DeadlineStatus,
    MatterUpdateProposalStatus,
)
from legal_workbench.domain.matters import (
    LegalMatter,
    MatterUpdateProposal,
)
from legal_workbench.domain.work_items import (
    Deadline,
    PriorityConfirmation,
    WorkItem,
    WorkItemDependency,
)

__all__ = [
    "DeadlineRepository",
    "DependencyRepository",
    "LegalMatterRepository",
    "MatterUpdateProposalRepository",
    "PriorityConfirmationRepository",
    "WorkItemRepository",
]

class LegalMatterRepository(Protocol):
    async def add(self, matter: LegalMatter) -> None: ...
    async def get(self, matter_id: UUID) -> LegalMatter | None: ...
    async def get_for_update(self, matter_id: UUID) -> LegalMatter | None: ...
    async def save(self, matter: LegalMatter) -> None: ...
    async def list(self, *, owner_id: str | None, limit: int) -> Sequence[LegalMatter]: ...


class MatterUpdateProposalRepository(Protocol):
    async def add(self, proposal: MatterUpdateProposal) -> None: ...
    async def get(self, proposal_id: UUID) -> MatterUpdateProposal | None: ...
    async def get_for_update(self, proposal_id: UUID) -> MatterUpdateProposal | None: ...
    async def save(self, proposal: MatterUpdateProposal) -> None: ...
    async def list(
        self,
        *,
        status: MatterUpdateProposalStatus | None,
        matter_id: UUID | None,
        limit: int,
    ) -> Sequence[MatterUpdateProposal]: ...


class WorkItemRepository(Protocol):
    async def add(self, work_item: WorkItem) -> None: ...
    async def add_many(self, work_items: Sequence[WorkItem]) -> None: ...
    async def get(self, work_item_id: UUID) -> WorkItem | None: ...
    async def get_for_update(self, work_item_id: UUID) -> WorkItem | None: ...
    async def save(self, work_item: WorkItem) -> None: ...
    async def list_by_matter(self, matter_id: UUID) -> Sequence[WorkItem]: ...


class PriorityConfirmationRepository(Protocol):
    async def add(self, confirmation: PriorityConfirmation) -> None: ...
    async def list_by_work_item(self, work_item_id: UUID) -> Sequence[PriorityConfirmation]: ...


class DeadlineRepository(Protocol):
    async def add(self, deadline: Deadline) -> None: ...
    async def list_by_work_item(
        self, work_item_id: UUID, *, status: DeadlineStatus | None = None
    ) -> Sequence[Deadline]: ...
    async def list_by_matter(
        self, matter_id: UUID, *, status: DeadlineStatus | None = None
    ) -> Sequence[Deadline]: ...


class DependencyRepository(Protocol):
    async def add(self, dependency: WorkItemDependency) -> None: ...
    async def get_for_update(self, dependency_id: UUID) -> WorkItemDependency | None: ...
    async def save(self, dependency: WorkItemDependency) -> None: ...
    async def list_by_work_item(self, work_item_id: UUID) -> Sequence[WorkItemDependency]: ...
