from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from legal_workbench.domain.setup import (
    IntegrationCheckRun,
    IntegrationCredential,
    IntegrationScope,
    SystemSetting,
)

__all__ = [
    "SetupRepository",
]

class SetupRepository(Protocol):
    async def get_setting(self, key: str) -> SystemSetting | None: ...
    async def save_setting(self, value: SystemSetting) -> None: ...
    async def get_credential(
        self, *, provider: str, credential_kind: str
    ) -> IntegrationCredential | None: ...
    async def save_credential(self, value: IntegrationCredential) -> None: ...
    async def list_scopes(self, *, provider: str) -> Sequence[IntegrationScope]: ...
    async def find_scope(
        self, *, provider: str, external_scope_id: str
    ) -> IntegrationScope | None: ...
    async def get_scope(self, scope_id: UUID) -> IntegrationScope | None: ...
    async def get_scope_for_update(self, scope_id: UUID) -> IntegrationScope | None: ...
    async def add_scope(self, value: IntegrationScope) -> None: ...
    async def save_scope(self, value: IntegrationScope) -> None: ...
    async def add_check(self, value: IntegrationCheckRun) -> None: ...
    async def get_check(self, check_run_id: UUID) -> IntegrationCheckRun | None: ...
    async def get_check_for_update(self, check_run_id: UUID) -> IntegrationCheckRun | None: ...
    async def save_check(self, value: IntegrationCheckRun) -> None: ...
    async def latest_check(
        self, *, provider: str, check_kind: str
    ) -> IntegrationCheckRun | None: ...
