from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from datetime import datetime
from types import TracebackType
from typing import Protocol
from uuid import UUID

from legal_workbench.domain.entities import (
    AgentAttemptLease,
    AgentDefinition,
    AgentRun,
    AgentRunAttempt,
    AgentRunSource,
    AgentRunStatusChange,
    AuditEvent,
    CandidateRevision,
    Communication,
    ContextSnapshot,
    Deadline,
    DocumentExtraction,
    DocumentSegment,
    DocumentVersion,
    DraftArtifact,
    FeishuAttachment,
    FeishuMessage,
    FeishuMessageVersion,
    FeishuRawEvent,
    IdempotencyRecord,
    IntegrationConnection,
    LegalMatter,
    MatterUpdateProposal,
    MessageAttachment,
    MessageCandidate,
    OutboxEvent,
    PriorityConfirmation,
    ReviewPackage,
    ReviewRecord,
    WorkItem,
    WorkItemDependency,
)
from legal_workbench.domain.enums import (
    AgentAttemptStatus,
    AgentRunStatus,
    CandidateMatterRelation,
    CandidateStatus,
    CommunicationStatus,
    DeadlineStatus,
    FeishuMessageStatus,
    MatterUpdateProposalStatus,
    ReviewPackageStatus,
)


class ContextSnapshotRepository(Protocol):
    async def add(self, snapshot: ContextSnapshot) -> None: ...
    async def get(self, snapshot_id: UUID) -> ContextSnapshot | None: ...
    async def find_by_source_hash(
        self, *, source_type: str, source_id: str, content_hash: str
    ) -> ContextSnapshot | None: ...


class MessageCandidateRepository(Protocol):
    async def add(self, candidate: MessageCandidate) -> None: ...
    async def get(self, candidate_id: UUID) -> MessageCandidate | None: ...
    async def get_for_update(self, candidate_id: UUID) -> MessageCandidate | None: ...
    async def save(self, candidate: MessageCandidate) -> None: ...
    async def list(
        self, *, status: CandidateStatus | None, limit: int
    ) -> Sequence[MessageCandidate]: ...
    async def link_to_matter(
        self,
        *,
        candidate_id: UUID,
        matter_id: UUID,
        relation_type: CandidateMatterRelation,
        confirmed_by: str,
    ) -> None: ...
    async def get_active_for_message(self, message_id: UUID) -> MessageCandidate | None: ...
    async def append_revision(self, revision: CandidateRevision) -> None: ...
    async def list_revisions(self, candidate_id: UUID) -> Sequence[CandidateRevision]: ...


class AgentDefinitionRepository(Protocol):
    async def add(self, definition: AgentDefinition) -> None: ...
    async def get(self, definition_id: UUID) -> AgentDefinition | None: ...
    async def get_active(self, key: str) -> AgentDefinition | None: ...


class AgentRunRepository(Protocol):
    async def add(self, run: AgentRun) -> None: ...
    async def get(self, run_id: UUID) -> AgentRun | None: ...
    async def get_for_update(self, run_id: UUID) -> AgentRun | None: ...
    async def save(self, run: AgentRun) -> None: ...
    async def list(self, *, status: AgentRunStatus | None, limit: int) -> Sequence[AgentRun]: ...
    async def list_by_message(self, message_id: UUID) -> Sequence[AgentRun]: ...
    async def list_status_events(self, run_id: UUID) -> Sequence[AgentRunStatusChange]: ...
    async def list_stale(
        self,
        *,
        statuses: Sequence[AgentRunStatus],
        older_than: datetime,
        limit: int,
    ) -> Sequence[AgentRun]: ...


class AgentRunAttemptRepository(Protocol):
    async def add(self, attempt: AgentRunAttempt) -> None: ...
    async def heartbeat(
        self,
        lease: AgentAttemptLease,
        *,
        heartbeat_at: datetime,
        lease_expires_at: datetime,
    ) -> None: ...
    async def complete(self, lease: AgentAttemptLease, *, finished_at: datetime) -> None: ...
    async def fail(
        self,
        lease: AgentAttemptLease,
        *,
        status: AgentAttemptStatus,
        failure_code: str,
        failure_message: str,
        finished_at: datetime,
    ) -> None: ...
    async def expire_current(
        self,
        *,
        run_id: UUID,
        attempt_number: int,
        finished_at: datetime,
    ) -> bool: ...
    async def list_by_run(self, run_id: UUID) -> Sequence[AgentRunAttempt]: ...


class AgentRunSourceRepository(Protocol):
    async def add_many(self, sources: Sequence[AgentRunSource]) -> None: ...
    async def list_by_run(self, run_id: UUID) -> Sequence[AgentRunSource]: ...


class DraftArtifactRepository(Protocol):
    async def add(self, artifact: DraftArtifact) -> None: ...


class LegalMatterRepository(Protocol):
    async def add(self, matter: LegalMatter) -> None: ...
    async def get(self, matter_id: UUID) -> LegalMatter | None: ...
    async def get_for_update(self, matter_id: UUID) -> LegalMatter | None: ...
    async def save(self, matter: LegalMatter) -> None: ...
    async def list(self, *, owner_id: str | None, limit: int) -> Sequence[LegalMatter]: ...


class MatterUpdateProposalRepository(Protocol):
    async def add(self, proposal: MatterUpdateProposal) -> None: ...
    async def get(self, proposal_id: UUID) -> MatterUpdateProposal | None: ...
    async def get_for_update(self, proposal_id: UUID) -> MatterUpdateProposal | None: ...
    async def save(self, proposal: MatterUpdateProposal) -> None: ...
    async def list(
        self,
        *,
        status: MatterUpdateProposalStatus | None,
        matter_id: UUID | None,
        limit: int,
    ) -> Sequence[MatterUpdateProposal]: ...


class WorkItemRepository(Protocol):
    async def add(self, work_item: WorkItem) -> None: ...
    async def add_many(self, work_items: Sequence[WorkItem]) -> None: ...
    async def get(self, work_item_id: UUID) -> WorkItem | None: ...
    async def get_for_update(self, work_item_id: UUID) -> WorkItem | None: ...
    async def save(self, work_item: WorkItem) -> None: ...
    async def list_by_matter(self, matter_id: UUID) -> Sequence[WorkItem]: ...


class PriorityConfirmationRepository(Protocol):
    async def add(self, confirmation: PriorityConfirmation) -> None: ...
    async def list_by_work_item(self, work_item_id: UUID) -> Sequence[PriorityConfirmation]: ...


class DeadlineRepository(Protocol):
    async def add(self, deadline: Deadline) -> None: ...
    async def list_by_work_item(
        self, work_item_id: UUID, *, status: DeadlineStatus | None = None
    ) -> Sequence[Deadline]: ...
    async def list_by_matter(
        self, matter_id: UUID, *, status: DeadlineStatus | None = None
    ) -> Sequence[Deadline]: ...


class DependencyRepository(Protocol):
    async def add(self, dependency: WorkItemDependency) -> None: ...
    async def list_by_work_item(self, work_item_id: UUID) -> Sequence[WorkItemDependency]: ...


class ReviewPackageRepository(Protocol):
    async def add(self, package: ReviewPackage) -> None: ...
    async def get(self, package_id: UUID) -> ReviewPackage | None: ...
    async def get_for_update(self, package_id: UUID) -> ReviewPackage | None: ...
    async def save(self, package: ReviewPackage) -> None: ...
    async def list(
        self, *, status: ReviewPackageStatus | None, matter_id: UUID | None, limit: int
    ) -> Sequence[ReviewPackage]: ...


class ReviewRecordRepository(Protocol):
    async def add(self, record: ReviewRecord) -> None: ...
    async def get(self, record_id: UUID) -> ReviewRecord | None: ...
    async def get_latest_approved(self, package_id: UUID) -> ReviewRecord | None: ...
    async def list_by_package(self, package_id: UUID) -> Sequence[ReviewRecord]: ...


class CommunicationRepository(Protocol):
    async def add(self, communication: Communication) -> None: ...
    async def get(self, communication_id: UUID) -> Communication | None: ...
    async def get_for_update(self, communication_id: UUID) -> Communication | None: ...
    async def get_by_review_record(self, review_record_id: UUID) -> Communication | None: ...
    async def list(
        self, *, status: CommunicationStatus | None, limit: int
    ) -> Sequence[Communication]: ...


class FeishuRepository(Protocol):
    async def get_event_by_external_id(
        self, event_id: str, *, tenant_key: str | None = None
    ) -> FeishuRawEvent | None: ...
    async def add_event(self, event: FeishuRawEvent) -> None: ...
    async def get_message(
        self, *, tenant_key: str | None, message_id: str
    ) -> FeishuMessage | None: ...
    async def add_message(self, message: FeishuMessage) -> None: ...
    async def get_message_by_id(self, message_id: UUID) -> FeishuMessage | None: ...
    async def get_message_for_update(self, message_id: UUID) -> FeishuMessage | None: ...
    async def list_context_messages(
        self, message: FeishuMessage, *, limit: int
    ) -> Sequence[FeishuMessage]: ...
    async def list_messages(
        self,
        *,
        statuses: Sequence[FeishuMessageStatus] | None,
        search: str | None,
        chat_id: str | None,
        created_from: datetime | None,
        created_to: datetime | None,
        limit: int,
    ) -> Sequence[FeishuMessage]: ...
    async def save_message(self, message: FeishuMessage) -> None: ...
    async def next_message_revision(self, message_id: UUID) -> int: ...
    async def add_message_version(self, version: FeishuMessageVersion) -> None: ...
    async def list_message_versions(self, message_id: UUID) -> Sequence[FeishuMessageVersion]: ...
    async def add_attachments(self, attachments: Sequence[FeishuAttachment]) -> None: ...
    async def list_pending_attachments(self, message_id: UUID) -> Sequence[FeishuAttachment]: ...
    async def list_attachments(self, message_id: UUID) -> Sequence[FeishuAttachment]: ...
    async def get_attachment_for_update(self, attachment_id: UUID) -> MessageAttachment | None: ...
    async def save_attachment(self, attachment: FeishuAttachment) -> None: ...
    async def list_queued_without_active_run(self, *, limit: int) -> Sequence[FeishuMessage]: ...
    async def get_connection(
        self, *, integration_type: str, connection_mode: object
    ) -> IntegrationConnection | None: ...
    async def save_connection(self, connection: IntegrationConnection) -> None: ...


class AuditEventRepository(Protocol):
    async def add(self, event: AuditEvent) -> None: ...


class OutboxEventRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...
    async def exists_pending(self, *, event_type: str, aggregate_id: UUID) -> bool: ...


class IdempotencyRepository(Protocol):
    async def get(self, *, operation: str, key: str) -> IdempotencyRecord | None: ...
    async def add(self, record: IdempotencyRecord) -> None: ...


class DocumentRepository(Protocol):
    async def find_version(
        self, *, attachment_id: UUID, content_sha256: str
    ) -> DocumentVersion | None: ...
    async def next_version(self, attachment_id: UUID) -> int: ...
    async def add_version(self, version: DocumentVersion) -> None: ...
    async def add_extraction(self, extraction: DocumentExtraction) -> None: ...
    async def find_latest_extraction(
        self, document_version_id: UUID
    ) -> DocumentExtraction | None: ...
    async def get_extraction_for_update(self, extraction_id: UUID) -> DocumentExtraction | None: ...
    async def save_extraction(self, extraction: DocumentExtraction) -> None: ...
    async def get_version(self, version_id: UUID) -> DocumentVersion | None: ...
    async def add_segments(self, segments: Sequence[DocumentSegment]) -> None: ...
    async def list_latest_segments(
        self, attachment_ids: Sequence[UUID]
    ) -> Sequence[DocumentSegment]: ...


class AttachmentStorageQuotaRepository(Protocol):
    async def reserve(
        self,
        *,
        attachment_id: UUID,
        requested_bytes: int,
        total_bytes: int,
        observed_used_bytes: int,
        expires_at: datetime,
    ) -> UUID | None: ...
    async def commit(self, reservation_token: UUID) -> None: ...
    async def release(self, reservation_token: UUID) -> None: ...


class UnitOfWork(Protocol):
    context_snapshots: ContextSnapshotRepository
    candidates: MessageCandidateRepository
    agent_definitions: AgentDefinitionRepository
    agent_runs: AgentRunRepository
    agent_run_attempts: AgentRunAttemptRepository
    agent_run_sources: AgentRunSourceRepository
    draft_artifacts: DraftArtifactRepository
    matters: LegalMatterRepository
    matter_update_proposals: MatterUpdateProposalRepository
    work_items: WorkItemRepository
    priority_confirmations: PriorityConfirmationRepository
    deadlines: DeadlineRepository
    dependencies: DependencyRepository
    review_packages: ReviewPackageRepository
    review_records: ReviewRecordRepository
    communications: CommunicationRepository
    feishu: FeishuRepository
    documents: DocumentRepository
    storage_quota: AttachmentStorageQuotaRepository
    audit_events: AuditEventRepository
    outbox_events: OutboxEventRepository
    idempotency: IdempotencyRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...
    async def lock_idempotency(self, *, operation: str, key: str) -> None: ...
    async def flush(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...


class AgentRuntime(Protocol):
    async def execute(self, run_id: str) -> None: ...


class EventPublisher(Protocol):
    async def publish_pending(self) -> AsyncIterator[str]: ...
